uptrain-ai/uptrain

oodles/core/classes/framework.py, oodles/core/classes/helpers/config_handler.py, setup.py
=> Using Pydantic for Dictionary syntax checks

setup.py, uptrain/core/classes/anomalies/data_drift.py, uptrain/core/classes/distances/distance_resolver.py, uptrain/core/classes/signals/signal_manager.py, uptrain/core/lib/datastores.py, uptrain/core/lib/test_datastores.py
An initial api to write logs to a local sqlite database.
=> sqlite persistence

.gitignore, examples/fraud_detection/run.ipynb, uptrain/core/classes/logging/st_run.py
closes https://github.com/uptrain-ai/uptrain/issues/93
This is because of the usage of python inbuilt split method. I've fixed it by using the os library's split method to split the files
=> Fixed the file split in st_run

uptrain/core/classes/visuals/tsne.py, uptrain/tests/test_dashboard.py
all available arguments for sklearn-tSNE are available to be passed on from config
=> added all hyperparameter arguments for tsne

examples/finetuning_LLM/run.ipynb, examples/fraud_detection/README.md, examples/fraud_detection/run.ipynb, examples/human_orientation_classification/deepdive_examples/uptrain_check_all.ipynb, examples/human_orientation_classification/deepdive_examples/uptrain_concept_drift.ipynb, examples/human_orientation_classification/deepdive_examples/uptrain_data_integrity.ipynb, examples/human_orientation_classification/run.ipynb, examples/ride_time_estimation/run.ipynb, examples/shopping_cart_recommendation/README.md, examples/shopping_cart_recommendation/run.ipynb, examples/text_summarization/run.ipynb, uptrain/core/classes/framework.py, uptrain/core/classes/helpers/config_handler.py, uptrain/core/classes/logging/log_handler.py, uptrain/tests/test_dashboard.py
=> Move logging-related args under logging args

uptrain/core/classes/anomalies/__init__.py, uptrain/core/classes/anomalies/model_bias.py, uptrain/core/classes/managers/check_manager.py
This resolves issue #110. Please review it. Thanks!
=> Changes Variable Name <Recommendation Bias> to <Model Bias>

CONTRIBUTING.md
Minor changes were made to provide newcomers with a better understanding of how to contribute and to avoid silly mistakes while pushing.
=> Minor changes in contributing.md

examples/human_orientation_classification/run_background.py, uptrain/core/classes/framework.py, uptrain/core/classes/helpers/config_handler.py
Create a background thread which runs all the analysis
=> Run in background

uptrain/tests/test_concept_drift_custom_monitor.py
This PR splits the test cases of concept drift into 2 separate test cases as mentioned in this https://github.com/uptrain-ai/uptrain/issues/156 issue.
=> split tests for ddm and custom monitor

.gitignore
Some local files from testing show up in `git add` completion. I have restructured the gitignore file and added onto it so that unwanted files (such as datasets) don't show up.
=> Restructure .gitignore

uptrain/core/classes/distances/__init__.py, uptrain/core/classes/distances/abstract.py, uptrain/core/classes/distances/cosine_distance.py, uptrain/core/classes/distances/l2_distance.py, uptrain/core/classes/distances/norm_ratio.py
This PR adds some documentation and type hints to the files in uptrain/core/classes/distances. Hopefully, it will make it easier for new contributors to understand what the code does.
Additionally, the distance classes inherit from a super class called `AbstractDistance` to make API consistent with how it is defined for other abstract bases in other files.
=> Add documentation and type hints to uptrain.core.classes.distances

docs/mint.json, docs/visuals/plot.mdx
This PR adds documentation for Visuals Plot API.
=> Add documentation for Visuals Plot

uptrain/core/classes/logging/log_streamlit.py, uptrain/core/classes/logging/st_run.py, uptrain/core/classes/monitors/concept_drift.py, uptrain/tests/test_a-b_testing.py
This PR adds a new test for A/B testing using the `model_args` feature and concept drift detection using ADWIN.
This PR is currently broken and needs a fix for streamlit plots. Discussed in private chat.
=> Add test for a/b testing

uptrain/core/classes/logging/new_log_handler.py, uptrain/core/classes/logging/new_st_run.py, uptrain/core/classes/managers/check_manager.py, uptrain/core/classes/statistics/convergence.py, uptrain/core/classes/statistics/distance.py, uptrain/core/classes/statistics/distribution.py, uptrain/core/classes/statistics/norm_embedding.py, uptrain/core/classes/visuals/__init__.py, uptrain/core/classes/visuals/dimensionality_reduction.py, uptrain/core/classes/visuals/shap.py, uptrain/core/lib/helper_funcs.py, uptrain/io/__init__.py, uptrain/io/binary.py, uptrain/io/text.py, uptrain/tests/test_visuals_dimensionality_reduction.py
=> add new logging method to umap/tsne checks

setup.py, uptrain/core/classes/logging/new_st_run.py, uptrain/core/classes/visuals/dimensionality_reduction.py, uptrain/tests/test_visuals_dimensionality_reduction.py
=> Allowing multiple coloring options in dimensionality reduction

uptrain/core/classes/logging/new_log_handler.py, uptrain/core/classes/measurables/distance.py, uptrain/core/classes/statistics/convergence.py, uptrain/core/classes/statistics/distance.py
=> create a unique logger per file rather than multiple

uptrain/core/classes/logging/new_log_handler.py, uptrain/core/lib/helper_funcs.py
=> small fixes to deps checking decorator and json logging

uptrain/core/classes/logging/st_run.py, uptrain/core/classes/visuals/dimensionality_reduction.py, uptrain/tests/test_visuals_dimensionality_reduction.py
=> Label coloring bug fix and HDBSCAN clustering

uptrain/core/classes/logging/new_st_run.py, uptrain/core/lib/helper_funcs.py
=> check if logs are actually present

setup.py, uptrain/tests/test_recommender_bias.py
- Updated the tests_require list in setup.py
- Renamed `test_rec_bias` to `test_recommender_bias` for clarity
=> Update setup.py and recommender bias test

uptrain/__init__.py, uptrain/constants.py, uptrain/core/classes/visuals/__init__.py, uptrain/core/classes/visuals/clustering.py, uptrain/core/classes/visuals/dimensionality_reduction.py, uptrain/tests/test_visuals_dimensionality_reduction.py
This PR adds Clustering Resolver to allow clustering algorithm to be passed as a config parameter. User is also given control over the parameters of clustering algorithm instead of using the fixed default. Dimensionality Reduction test is updated accordingly.
=> Add ClusteringResolver, Update Dimensionality Reduction Test

uptrain/core/classes/visuals/clustering.py
=> use strings to type, not objects

examples/refactor/test_developer_docs.py, regression_testing/experiment.py, uptrain/io/__init__.py, uptrain/io/writers.py, uptrain/operators/language/__init__.py, uptrain/operators/language/not_implemented.py
=> Add testing config file for developer docs testing

examples/integrations/test_bq_integration.py, setup.py, uptrain/core/classes/framework.py, uptrain/core/classes/helpers/config_handler.py, uptrain/core/classes/io/__init__.py, uptrain/core/classes/io/runtime_manager.py
New mode to run UpTrain monitoring endlessly by querying Bigquery with time-dependent filters
=> Changes for running UpTrain endlessly by periodically querying rds

examples/integrations/test_postgres_integration.py, uptrain/core/classes/helpers/config_handler.py, uptrain/core/classes/io/runtime_manager.py, uptrain/core/classes/logging/log_handler.py, uptrain/core/classes/logging/log_postgres.py, uptrain/core/classes/monitors/data_integrity.py
- New feature (non-breaking change which adds functionality)
Capability to read periodically read from a postgres table
Capability to write logs to a postgres table
Added example to demonstrate above integration
Minor fixes in data integrity check
=> Allow reading directly from postgres table as well as logging to postgres

examples/prompt-experiments.ipynb, uptrain/operators/language/generation.py
=> Add changes to prompt experiments

README.md, docs/api-reference/README.md, docs/getting-started/quickstart.mdx, docs/tutorials/openai-evals.mdx, docs/tutorials/prompt-experiments.mdx, docs/tutorials/validation.mdx, examples/openai_evals_tutorial.ipynb, examples/prompt_experiments_tutorial.ipynb, examples/refactor/qna-logs-eval.ipynb, examples/refactor/quality-monitoring.ipynb, examples/refactor/sql_test.py, examples/refactor/test_docs.py, examples/refactor/test_model_grading.py, examples/refactor/test_w_client.py, examples/validation_tutorial.ipynb, uptrain/dashboard/st_helpers.py, uptrain/framework/checks.py
=> Add a table for consolidated results

pyproject.toml, uptrain/MANIFEST.in
apparently true by default but wasnt working for us - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
=> add directive to include stub files

uptrain/framework/__init__.pyi, uptrain/framework/checks.py, uptrain/framework/remote.py, uptrain/operators/__init__.pyi, uptrain/operators/io/readers.py, uptrain/operators/language/generation.py, uptrain/operators/language/llm.py, uptrain/operators/language/model_grade.py, uptrain/operators/language/text.py, uptrain/operators/table.py, uptrain/operators/vis.py
=> Add experiment args 

tests/test_builtins.py, uptrain/framework/base.py, uptrain/framework/builtins.py, uptrain/operators/__init__.pyi, uptrain/operators/language/critique.py, uptrain/operators/language/with_context.py
=> Make changes to evals

uptrain/framework/remote.py, uptrain/operators/io/bq.py
=> Increase timeout, add retries + limit for BQ

uptrain/operators/language/model_grade.py
=> Model grade evals

uptrain/operators/__init__.pyi, uptrain/operators/language/with_context.py
=> Add new eval - Response completeness wrt context

tests/test_operators.py, uptrain/operators/chart.py
Feature Enhancement: Added Description to Chart Visualization
This pull request introduces a new feature that allows adding descriptions to chart visualizations, enhancing their context and understanding. Descriptions are now supported not only for the MultiPlot operator but also for individual chart types like LineChart, ScatterPlot, BarChart, Histogram, and CustomPlotlyChart. Additionally, this update includes comprehensive docstrings for the affected classes in the operator section, providing clear usage instructions.
Changes:
- Added description feature to chart visualizations
- Descriptions supported for MultiPlot and individual chart types
- Comprehensive docstrings added for certain classes in operators
Please review and merge.
=> Added description feature to chart visuailization along with doc strings for certain classes in operator section

get_started.py, pyproject.toml, uptrain/framework/__init__.pyi, uptrain/framework/builtins.py, uptrain/framework/remote.py
=> Simple script to get started

uptrain/framework/checks.py
=> Fix unnecessary import msg

uptrain/framework/__init__.pyi, uptrain/framework/builtins.py, uptrain/framework/evals.py, uptrain/framework/remote.py, uptrain/operators/__init__.pyi, uptrain/operators/language/guideline.py, uptrain/operators/language/model_grade.py
=> Add a new check to evaluate if the LLM is following a guideline or not

uptrain/framework/checks.py, uptrain/operators/__init__.pyi, uptrain/operators/io/base.py, uptrain/operators/io/bq.py
=> Add ability for postprocessors

uptrain/operators/__init__.pyi, uptrain/operators/clustering.py, uptrain/operators/embs.py, uptrain/operators/language/embedding.py, uptrain/operators/language/generation.py, uptrain/operators/language/llm.py
1. Added a new operator for clustering. 
2. Added a new operator for finding a common topic across different queries.
=> kmeans clustering

get_started_managed.py, pyproject.toml, uptrain/cli.py, uptrain/dashboard/st_helpers.py, uptrain/dashboard/st_run.py, uptrain/framework/evalllm.py, uptrain/operators/base.py, uptrain/operators/chart.py, uptrain/operators/io/base.py, uptrain/operators/language/llm.py, uptrain/utilities/__init__.py
=> Reduce dependencies

uptrain/cli.py, uptrain/framework/base.py, uptrain/framework/remote.py, uptrain/operators/__init__.pyi, uptrain/operators/clustering.py, uptrain/operators/language/embedding.py, uptrain/operators/language/generation.py, uptrain/operators/language/llm.py, uptrain/operators/language/topic.py, uptrain/operators/table.py
Add ability to do embedding clustering, and identify common topics
=> Topic cluster

uptrain/framework/builtins.py, uptrain/framework/evals.py, uptrain/framework/remote.py, uptrain/operators/__init__.pyi, uptrain/operators/language/with_context.py
Added Chaotic Response Operator 
=> chaotic response val added

uptrain/framework/builtins.py, uptrain/framework/evals.py, uptrain/framework/remote.py, uptrain/operators/__init__.pyi, uptrain/operators/language/with_context.py
Response Conciseness Eval added
=> concise response eval added

uptrain/operators/language/model_grade.py
LLM Score extraction method updated.
=> score extract method updated

uptrain/operators/language/embedding.py
=> Add batching for embeddings

examples/benchmarking_results.ipynb
Benchmarking results for Uptrain standard evals on FiQA dataset.
=> benchmarking results

uptrain/operators/language/generation.py, uptrain/operators/language/model_grade.py
model name picking from the settings object.
=> model param removed

uptrain/framework/__init__.pyi, uptrain/framework/builtins.py, uptrain/framework/evalllm.py, uptrain/framework/evals.py, uptrain/framework/remote.py, uptrain/operators/__init__.pyi, uptrain/operators/language/conversation.py
Added an eval for conversation assessment.
=> Conversation eval

uptrain/operators/__init__.pyi, uptrain/operators/io/mongodb.py
=> mongodb reader operator added

uptrain/framework/base.py, uptrain/operators/language/embedding.py
local_run variable defined in settings
=> local run variable added in settings

uptrain/framework/base.py, uptrain/operators/language/embedding.py
putting a constraint on text length for embedding computation
=> text limit added

uptrain/operators/language/embedding.py
=> fix embedding operator

uptrain/operators/io/mongodb.py
=> mongodb operator updated

uptrain/framework/remote.py, uptrain/operators/language/with_context.py
=> settings added in API Client

uptrain/operators/io/base.py
=> json reader operator update

uptrain/operators/io/mongodb.py
=> Add fix for mongo read operator

uptrain/operators/language/conversation.py, uptrain/operators/language/critique.py, uptrain/operators/language/guideline.py, uptrain/operators/language/response_matching.py
=> col_out var added

uptrain/framework/builtins.py, uptrain/framework/evalllm.py, uptrain/framework/evals.py, uptrain/framework/remote.py, uptrain/operators/__init__.pyi, uptrain/operators/language/response_matching.py
=> valid response operator added

uptrain/framework/base.py
=> Change default model

uptrain/framework/evals.py, uptrain/framework/remote.py, uptrain/operators/language/llm.py, uptrain/operators/language/model_grade.py
=> Add new evals 

uptrain/framework/builtins.py, uptrain/framework/evalllm.py, uptrain/framework/evals.py, uptrain/framework/remote.py, uptrain/operators/__init__.pyi, uptrain/operators/language/guideline.py
=> prompt injection operator added

uptrain/operators/language/model_grade.py
=> Add parsing for scoring evals

uptrain/framework/base.py
=> response_format added

uptrain/operators/language/llm.py
=> Increase timeout

uptrain/__init__.pyi, uptrain/framework/__init__.pyi, uptrain/framework/evalllm.py, uptrain/framework/evals.py, uptrain/framework/remote.py
=> Custom prompt eval

uptrain/framework/evalllm.py, uptrain/framework/remote.py, uptrain/operators/language/guideline.py, uptrain/operators/language/response_matching.py, uptrain/operators/language/with_context.py
=> scenario_description_added

uptrain/__init__.pyi, uptrain/framework/__init__.pyi, uptrain/framework/rca_templates.py, uptrain/framework/remote.py
=> Add capability to perform root cause analysis

uptrain/framework/remote.py, uptrain/operators/__init__.pyi, uptrain/operators/language/conversation.py, uptrain/operators/language/critique.py, uptrain/operators/language/guideline.py, uptrain/operators/language/llm.py, uptrain/operators/language/response_matching.py, uptrain/operators/language/with_context.py, uptrain/operators/rca/rag_with_citation.py, uptrain/utilities/__init__.py
=> rag_citation operator added

uptrain/framework/remote.py
=> Increase chunk size for evaluate to 100

examples/integrations/spade/evaluating_guidelines_generated_by_spade.ipynb, examples/integrations/vector_db/chroma.ipynb
=> spade colab link update

uptrain/operators/code/detection.py
=> sending json

examples/checks/README.md, examples/checks/language_features/README.md, examples/checks/language_features/rouge_score.ipynb
=> rouge tutorial

examples/checks/safeguarding/jailbreak_detection.ipynb
=> jailbreak tutorial update

uptrain/framework/evalllm.py, uptrain/framework/remote.py
=> update req_attrs valid response

tests/test_builtins.py, uptrain/operators/language/jailbreak.py, uptrain/operators/language/prompts/classic.py, uptrain/operators/language/prompts/few_shots.py, uptrain/operators/language/prompts/output_format.py, uptrain/operators/language/response_quality.py
=> Push fixes for tests

README.md
=> readme link updates

uptrain/dev/frontend/dashboard/src/app/api-keys/page.js, uptrain/dev/frontend/dashboard/src/components/CreateProjectModal/CreateProjectModal.js, uptrain/dev/frontend/dashboard/src/components/CreateProjectModal/Step1.js, uptrain/dev/frontend/dashboard/src/store/reducers/userInfo.js
=> model api integration

examples/open_source_evaluator_tutorial.ipynb, uptrain/framework/base.py
=> mistral api integration

docs/faq/faq.mdx, docs/mint.json
=> updated faqs on doc

pyproject.toml, uptrain/framework/evalllm.py
=> Ashish fix 2

uptrain/operators/__init__.pyi, uptrain/operators/language/question_quality.py
=> Add Valid Question Operator

docs/predefined-evaluations/safeguarding/jailbreak.mdx
=> Fix variable name

pyproject.toml, uptrain/utilities/utils.py
=> Fix fsspec import error

uptrain/framework/evalllm.py
=> Experiments: Handling duplicates in data

uptrain/framework/evalllm.py, uptrain/utilities/utils.py
=> added openai api key validation

examples/integrations/vector_db/milvus.ipynb
=> Milvus Integration Cookbook

uptrain/operators/__init__.pyi, uptrain/operators/language/question_quality.py
=> add query rewrite operator

uptrain/operators/language/prompts/classic.py, uptrain/operators/language/prompts/output_format.py, uptrain/operators/language/question_quality.py
=> add open source prompt for query rewrite

uptrain/framework/remote.py
=> Api client modify

uptrain/framework/evalllm.py, uptrain/framework/evals.py
=> add question_completeness eval

docs/integrations/framework/llamaindex-methods/callback_handler/overview.mdx, docs/integrations/framework/llamaindex-methods/callback_handler/rag_query.mdx, docs/integrations/framework/llamaindex-methods/callback_handler/reranking.mdx, docs/integrations/framework/llamaindex-methods/callback_handler/subques_query.mdx, docs/integrations/framework/llamaindex-methods/overview.mdx
=> Link fixes in llamaindex

docs/predefined-evaluations/context-awareness/context-conciseness.mdx
I found a small error while reviewing the document, I hope this PR can help UpTrain, thanks.
No.
=> doc: fix error word in the context-conciseness.mdx

docs/integrations/observation-tools/zeno.mdx, examples/integrations/observation_tools/zeno.ipynb
PR #634 moved the location of `zeno.ipynb`. This PR adjusts sources to changes.
=> Update location of `zeno.ipynb`

uptrain/dashboard/frontend/dashboard/src/components/Evaluations/ChartPage/ChartPage.js, uptrain/dashboard/frontend/dashboard/src/components/Evaluations/Homepage/ProjectCard.js, uptrain/dashboard/frontend/dashboard/src/components/Evaluations/Homepage/ProjectSection.js, uptrain/dashboard/frontend/dashboard/src/components/Experiment/ChartPage/ChartSection.js, uptrain/dashboard/frontend/dashboard/src/components/Experiment/Homepage/ProjectCard.js, uptrain/dashboard/frontend/dashboard/src/components/Experiment/Homepage/ProjectSection.js
=> convert name to ids in url mapping

uptrain/operators/language/prompts/few_shots.py
Resolves: #529 
cc: @sourabhagr, @Dominastorm.
=> fix: update `PROMPT_INJECTION_FEW_SHOT__CLASSIFY` and `PROMPT_INJECTION_FEW_SHOT__COT` variables in few_shots.py

docs/getting-started/dashboard/getting_started.mdx, uptrain/operators/__init__.pyi, uptrain/operators/chart.py
=> feat: Add bubblechart class for visualization module
